# Generated by Django 5.2.15 on 2026-06-24 09:44

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "original_url",
                    models.URLField(blank=True, max_length=500, null=True, unique=True),
                ),
                (
                    "url_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("raw_input", models.TextField()),
                ("summary", models.TextField()),
                ("tags", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="post_status_pubdate_idx",
                    ),
                    models.Index(fields=["url_hash"], name="post_urlhash_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["tags"], name="post_tags_gin_idx"
                    ),
                ],
            },
        ),
    ]
