# Generated by Django 5.2.15 on 2026-06-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrutinize_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
