# Generated by Django 5.2.15 on 2026-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, default='', help_text='Enter up to 10 comma-separated keywords.')),
            ],
            options={
                'verbose_name': 'Keyword Settings',
                'verbose_name_plural': 'Keyword Settings',
            },
        ),
    ]
