# Generated by Django 5.2.15 on 2026-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_post_status_384c95_idx",
            old_name="posts_post_status_8de7d2_idx",
        ),
    ]
