# Generated by Django 5.2.15 on 2026-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts",
            "0002_rename_posts_post_status_8de7d2_idx_posts_post_status_384c95_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("published_at"), descending=True, nulls_last=True
                    ),
                    "-fetched_at",
                ]
            },
        ),
    ]
