# Generated by Django 5.2.15 on 2026-07-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_keywordsetting_and_more'),
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
    ]
