# Generated by Django 5.2.15 on 2026-07-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_scrutinize_file_id'),
        ('posts', '0004_merge_20260701_1533'),
    ]

    operations = [
    ]
