# Generated by Django 5.2.15 on 2026-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_merge_20260701_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default='', help_text='OpenAI-compatible API base URL, e.g. http://localhost:11434/v1 or your ngrok /v1 endpoint. Leave blank to use OPENAI_BASE_URL from .env.', max_length=500)),
                ('model_name', models.CharField(blank=True, default='', help_text='Local or remote model name, e.g. Qwen/Qwen3.5-4B. Leave blank to use LLM_MODEL from .env.', max_length=200)),
            ],
            options={
                'verbose_name': 'LLM Config',
                'verbose_name_plural': 'LLM Config',
            },
        ),
    ]
