# Generated by Django 5.2.15 on 2026-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('post_id', models.IntegerField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_posts',
                'unique_together': {('token', 'post_id')},
            },
        ),
    ]
